import type { Product, Category } from '@shared/types';
export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat1', name: 'Electronics', slug: 'electronics' },
  { id: 'cat2', name: 'Apparel', slug: 'apparel' },
  { id: 'cat3', name: 'Home Goods', slug: 'home-goods' },
  { id: 'cat4', name: 'Books', slug: 'books' },
];
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod1',
    name: 'Quantum Wireless Headphones',
    description: 'Experience immersive sound with these noise-cancelling wireless headphones. Featuring a 30-hour battery life and crystal-clear microphone.',
    price: 199.99,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d76e?q=80&w=2070&auto=format&fit=crop', 'https://images.unsplash.com/photo-1546435770-a3e426bf4022?q=80&w=2070&auto=format&fit=crop'],
    category: 'Electronics',
    vendorId: 'ven1',
    variants: [
      { id: 'var1a', name: 'Color', value: 'Black', sku: 'QWH-BLK', priceModifier: 0, stock: 50 },
      { id: 'var1b', name: 'Color', value: 'White', sku: 'QWH-WHT', priceModifier: 0, stock: 30 },
    ],
    tags: ['audio', 'wireless', 'tech'],
    rating: 4.8,
    reviewCount: 1250,
  },
  {
    id: 'prod2',
    name: 'AeroFlex Running Shoes',
    description: 'Lightweight and breathable running shoes designed for maximum comfort and performance. Perfect for road running and gym workouts.',
    price: 120.00,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=2070&auto=format&fit=crop', 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d34?q=80&w=1887&auto=format&fit=crop'],
    category: 'Apparel',
    vendorId: 'ven2',
    variants: [
      { id: 'var2a', name: 'Size', value: '9', sku: 'AFS-09', priceModifier: 0, stock: 20 },
      { id: 'var2b', name: 'Size', value: '10', sku: 'AFS-10', priceModifier: 0, stock: 15 },
      { id: 'var2c', name: 'Size', value: '11', sku: 'AFS-11', priceModifier: 0, stock: 18 },
    ],
    tags: ['footwear', 'sports', 'running'],
    rating: 4.6,
    reviewCount: 890,
  },
  {
    id: 'prod3',
    name: 'Minimalist Ceramic Vase',
    description: 'A beautifully crafted ceramic vase with a minimalist design. Adds a touch of elegance to any room.',
    price: 45.50,
    images: ['https://images.unsplash.com/photo-1588099768531-a72d4a198538?q=80&w=1887&auto=format&fit=crop', 'https://images.unsplash.com/photo-1588099768529-a9b3318fac3b?q=80&w=1887&auto=format&fit=crop'],
    category: 'Home Goods',
    vendorId: 'ven3',
    variants: [
      { id: 'var3a', name: 'Style', value: 'Matte', sku: 'MCV-MAT', priceModifier: 0, stock: 40 },
      { id: 'var3b', name: 'Style', value: 'Glossy', sku: 'MCV-GLS', priceModifier: 5, stock: 25 },
    ],
    tags: ['decor', 'home', 'pottery'],
    rating: 4.9,
    reviewCount: 450,
  },
  {
    id: 'prod4',
    name: 'The Alchemist\'s Secret',
    description: 'A thrilling fantasy novel about a young apprentice who uncovers a powerful, ancient secret. A must-read for fans of the genre.',
    price: 15.99,
    images: ['https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=1887&auto=format&fit=crop', 'https://images.unsplash.com/photo-1532012197267-da84d127e765?q=80&w=1887&auto=format&fit=crop'],
    category: 'Books',
    vendorId: 'ven4',
    variants: [
      { id: 'var4a', name: 'Format', value: 'Paperback', sku: 'TAS-PB', priceModifier: 0, stock: 100 },
      { id: 'var4b', name: 'Format', value: 'Hardcover', sku: 'TAS-HC', priceModifier: 10, stock: 50 },
    ],
    tags: ['fiction', 'fantasy', 'adventure'],
    rating: 4.5,
    reviewCount: 2300,
  },
  {
    id: 'prod5',
    name: 'Smart Garden Kit',
    description: 'Grow your own herbs and vegetables indoors with this automated smart garden. Includes everything you need to get started.',
    price: 89.99,
    images: ['https://images.unsplash.com/photo-1592205869446-98286470b926?q=80&w=1887&auto=format&fit=crop'],
    category: 'Home Goods',
    vendorId: 'ven3',
    variants: [
      { id: 'var5a', name: 'Size', value: '3-Pod', sku: 'SGK-3', priceModifier: 0, stock: 30 },
      { id: 'var5b', name: 'Size', value: '9-Pod', sku: 'SGK-9', priceModifier: 40, stock: 15 },
    ],
    tags: ['gardening', 'smart home', 'tech'],
    rating: 4.7,
    reviewCount: 620,
  },
  {
    id: 'prod6',
    name: 'Classic Denim Jacket',
    description: 'A timeless denim jacket that never goes out of style. Made from high-quality, durable denim for a comfortable fit.',
    price: 75.00,
    images: ['https://images.unsplash.com/photo-1596588146344-1ab21ae440a0?q=80&w=1887&auto=format&fit=crop'],
    category: 'Apparel',
    vendorId: 'ven2',
    variants: [
      { id: 'var6a', name: 'Size', value: 'M', sku: 'CDJ-M', priceModifier: 0, stock: 40 },
      { id: 'var6b', name: 'Size', value: 'L', sku: 'CDJ-L', priceModifier: 0, stock: 35 },
    ],
    tags: ['fashion', 'outerwear', 'classic'],
    rating: 4.8,
    reviewCount: 1500,
  },
  {
    id: 'prod7',
    name: 'Portable Espresso Maker',
    description: 'Enjoy delicious espresso anywhere with this compact and lightweight portable espresso maker. No batteries or electricity required.',
    price: 55.00,
    images: ['https://images.unsplash.com/photo-1621993202324-b93a3a58a6d4?q=80&w=1887&auto=format&fit=crop'],
    category: 'Home Goods',
    vendorId: 'ven1',
    variants: [
      { id: 'var7a', name: 'Color', value: 'Black', sku: 'PEM-BLK', priceModifier: 0, stock: 60 },
    ],
    tags: ['coffee', 'travel', 'kitchen'],
    rating: 4.9,
    reviewCount: 980,
  },
  {
    id: 'prod8',
    name: 'Cyberpunk 2088',
    description: 'The latest open-world RPG set in a dystopian future. Explore a vast city, customize your character, and shape your story.',
    price: 59.99,
    images: ['https://images.unsplash.com/photo-1555864416-762a4a0335b0?q=80&w=2070&auto=format&fit=crop'],
    category: 'Electronics',
    vendorId: 'ven4',
    variants: [
      { id: 'var8a', name: 'Platform', value: 'PC', sku: 'CP88-PC', priceModifier: 0, stock: 200 },
      { id: 'var8b', name: 'Platform', value: 'PS5', sku: 'CP88-PS5', priceModifier: 0, stock: 150 },
    ],
    tags: ['gaming', 'rpg', 'scifi'],
    rating: 4.2,
    reviewCount: 5400,
  },
];